### ISSUE TITLE
It's better to replace % to format

### ISSUE THREAD

**Issue by mczimm** [tanelpoder/0xtools#4]
https://github.com/tanelpoder/psnapper/blob/1682a1acccf98448805b4ad08686c524d742488c/proc.py#L368

For example:
return ['{} {}'.format(depth, stack_line) for depth, stack_line in enumerate(fh.readlines()[::-1])]

**Comment by tanelpoder** [comment]
What's he reasoning that it's better? (I'm not a python expert really and have been using only % so far).

I haven't actually externalized the stack backtrace reports yet, I'll probably take this on next.

**Comment by mczimm** [comment]
It's a new method which is more flexible.

https://www.python.org/dev/peps/pep-3101/#rationale

By the way I'm not an expert in the python too, but it's seems to be cool to be on the new wave)

**Comment by tanelpoder** [comment]
Thanks. Took a while to go through the updates & merges I had in mind. I won't implement this change as pSnapper will have to work on python2 in the foreseeable future, due to "enterprise production reality".

**Comment by tanelpoder** [comment]
I just looked/tested that this syntax indeed works on python 2 too (didn't realize that, great!). However I'll keep the code as is for now, as it already works without issues.
