### ISSUE TITLE
AlmaLinux 8.9.0 Please make sure you have the correct access rights and the repository exists.

### ISSUE THREAD

**Issue by mustafaerdinc** [tanelpoder/0xtools#44]
Hello,

I am getting following error when I try git clone on Alma Linux 8.9.0 

I couldn't make sure if error due to Alma Linux or 0xtools.git

Regards

`git clone git@github.com:tanelpoder/0xtools.git
Cloning into '0xtools'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

**Comment by tanelpoder** [comment]
My mistake, the publicly accessible URL for cloning is this (fixed in the webpage too):

```
git clone https://github.com/tanelpoder/0xtools.git
```
