### ISSUE TITLE
ubuntu 18 error while running make

### ISSUE THREAD

**Issue by moustafa1977** [tanelpoder/0xtools#9]
make
gcc -I include -Wall -o bin/xcapture src/xcapture.c
src/xcapture.c: In function ‘main’:
src/xcapture.c:392:41: warning: ‘%s’ directive writing up to 255 bytes into a region of size 94 [-Wformat-overflow=]
                 sprintf(dirpath, "/proc/%s", pde->d_name);
                                         ^~
src/xcapture.c:392:17: note: ‘sprintf’ output between 7 and 262 bytes into a destination of size 100
                 sprintf(dirpath, "/proc/%s", pde->d_name);
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/xcapture.c:401:49: warning: ‘%s’ directive writing up to 255 bytes into a region of size 94 [-Wformat-overflow=]
                         sprintf(dirpath, "/proc/%s/task", pde->d_name);
                                                 ^~
src/xcapture.c:401:25: note: ‘sprintf’ output between 12 and 267 bytes into a destination of size 100
                         sprintf(dirpath, "/proc/%s/task", pde->d_name);
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
root@sql3:/home/moustafa_ahmed/0xtools# lsb_release
No LSB modules are available.
root@sql3:/home/moustafa_ahmed/0xtools# cat /etc/issue
Ubuntu 18.04.5 LTS \n \l

**Comment by fleers** [comment]
Same on 20.04

**Comment by tanelpoder** [comment]
Yep, noted. These are compilation warnings, the build itself succeeds (xcapture will show up in the bin directory).

I'll fix these warnings in v1.1

**Comment by tanelpoder** [comment]
just (finally) pushed the fix to the main branch in the repo. haven't bumped up the version yet.
